export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MOVIE_ADD_REQUEST = 'MOVIE_ADD_REQUEST';
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
export const MOVIE_ADD_FAIL = 'MOVIE_ADD_FAIL';
export const MOVIE_ADD_RESET = 'MOVIE_ADD_RESET';

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_UPDATE_FAIL = 'MOVIE_UPDATE_FAIL';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL';
export const MOVIE_DELETE_RESET = 'MOVIE_DELETE_RESET';
