export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_QUESTION_PROCEED = 'USER_QUESTION_PROCEED';

export const USER_FORGET_REQUEST = 'USER_FORGET_REQUEST';
export const USER_FORGET_SUCCESS = 'USER_FORGET_SUCCESS';
export const USER_FORGET_FAIL = 'USER_FORGET_FAIL';
